kind = "web"
previewPath = "/"
title = "FILM ILEB LUO"
version = "1.0.0"
id = "artifacts/film-ileb-luo"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26109

[services.development]
run = "pnpm --filter @workspace/film-ileb-luo run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/film-ileb-luo", "run", "build" ]
publicDir = "artifacts/film-ileb-luo/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26109"
BASE_PATH = "/"
